## Поддержка и Донаты / Support the Project

Если вы хотите поддержать развитие проекта WT419, вы можете отправить криптовалюту на любой из кошельков ниже. Адреса оформлены кодом, чтобы их можно было скопировать в один клик:

* **USDT (сеть TRON / TRC-20):**  
  `TX2v8ruQFZwELC9oFcjLdRmn8zKPxV8WKF`  
  ![USDT](https://img.shields.io/badge/USDT-TRC20-green?style=flat-square&logo=tether)

* **TON (сеть The Open Network):**  
  `EQBcFx4Le5tuul6suQYcaVXWQ8RayQjXHENqjE83ZW-WH_Er`  
  ![TON](https://img.shields.io/badge/TON-Network-blue?style=flat-square&logo=the-open-network)

* **По вопросам коммерческой подписки или сотрудничества:** Связаться в [Telegram](https://t.me/Webterrorist419)
